# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build frontend

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use node.js 14.x
      uses: actions/setup-node@v1
      with:
        java-version: 14.x
    - name: npm install frontend
      run: |
        cd frontend
        npm install
    - name: run test
      run: |
        cd frontend
        npm run test
    - name: build frontend
      run: |
        cd frontend
        npm run build
